// Code generated by command: go run asm.go -out simd.s -stubs stub.go. DO NOT EDIT.

package simplesimd

func andSIMD(a []byte, b []byte, res []byte)

func orSIMD(a []byte, b []byte, res []byte)

func andnotSIMD(a []byte, b []byte, res []byte)
