// Code generated by command: go run asm.go -out simd.s -stubs stub.go. DO NOT EDIT.

package simplesimd

func andSIMD(a []byte, b []byte, res []byte)

func orSIMD(a []byte, b []byte, res []byte)

func andnotSIMD(a []byte, b []byte, res []byte)

func andScalar(a []byte, b []byte, res []byte)

func orScalar(a []byte, b []byte, res []byte)

func andnotScalar(a []byte, b []byte, res []byte)

func andScalarFaster(a []byte, b []byte, res []byte)

func orScalarFaster(a []byte, b []byte, res []byte)

func andnotScalarFaster(a []byte, b []byte, res []byte)
